# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
    - test
    - docker
    - build

sast:
    stage: test
include:
    - template: Security/SAST.gitlab-ci.yml

kaniko-cli:
    stage: docker
    before_script: []
    image:
        name: gcr.io/kaniko-project/executor:v1.14.0-debug
        entrypoint: ['']
    script:
        - |
            echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
            /kaniko/executor \
            --context "${CI_PROJECT_DIR}" \
            --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile.cli" \
            --destination "${CI_REGISTRY_IMAGE}/cli:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}" \
            --destination "${CI_REGISTRY_IMAGE}/cli:${CI_COMMIT_BRANCH}" \
            --cache=true \
            --cache-copy-layers=true \
            --cache-ttl=72h

kaniko-cli-main:
    stage: docker
    before_script: []
    only:
        - main
    image:
        name: gcr.io/kaniko-project/executor:v1.14.0-debug
        entrypoint: ['']
    script:
        - |
            echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
            /kaniko/executor \
            --context "${CI_PROJECT_DIR}" \
            --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile.cli" \
            --destination "${CI_REGISTRY_IMAGE}/cli:${CI_COMMIT_SHORT_SHA}" \
            --destination "${CI_REGISTRY_IMAGE}/cli:latest" \
            --cache=true \
            --cache-copy-layers=true \
            --cache-ttl=72h

build-cli:
    image: golang:alpine
    stage: build
    artifacts:
        expire_in: 1 day
        paths:
            - dist/stamusctl
    script:
        - |
            apk add --no-cache gcc musl-dev make
            make cli
