default:
    tags:
        - k8s-small

stages:
    - ut
    - build
    - func-test
    - deploy
    - integration

.go-cache:
    variables:
        GOPATH: $CI_PROJECT_DIR/.go
    before_script:
        - mkdir -p .go
    cache:
        paths:
            - .go/pkg/mod/

include:
    - local: gitlab/unit-tests.yml
    - local: gitlab/build.yml
    - local: gitlab/func-tests.yml
    - local: gitlab/release.yml
    - local: gitlab/integration-tests.yml