FROM golang:1.24-alpine3.20 AS builder

ARG var_version=devel
ENV VERSION=$var_version

RUN mkdir -p /src
RUN apk add --no-cache gcc musl-dev make
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY ./go.mod /src/stamus-ctl/go.mod
COPY ./go.sum /src/stamus-ctl/go.sum
WORKDIR /src/stamus-ctl
RUN go mod download

COPY . /src/stamus-ctl
RUN swag init --pd -g root.go -o cmd/docs -d cmd/daemon/run/ \
    && CGO_ENABLED=1 make cli


FROM docker:27.3.1-alpine3.20 AS docker

RUN /usr/local/bin/dockerd-entrypoint.sh || exit 0

FROM alpine:3.20

COPY --from=docker /certs /certs

RUN apk add --no-cache bash bash-completion

COPY --from=Builder /src/stamus-ctl/dist /bin/

RUN stamusctl completion bash > /etc/profile.d/stamusctl_completion.sh &&  echo "source /etc/profile.d/stamusctl_completion.sh" >> ~/.bashrc
