FROM golang:1.24-alpine AS builder

ARG var_version=devel
ENV VERSION=$var_version

RUN mkdir -p /src
RUN apk add --no-cache gcc musl-dev make
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY ./go.mod /src/stamus-ctl/go.mod
COPY ./go.sum /src/stamus-ctl/go.sum
WORKDIR /src/stamus-ctl
RUN go mod download

COPY . /src/stamus-ctl
RUN swag init --pd -g root.go -o cmd/docs -d cmd/daemon/run/
RUN CGO_ENABLED=1 make daemon

FROM docker
COPY --from=builder /src/stamus-ctl/dist /bin/

ENTRYPOINT [ "stamusd" ]
CMD [ "run" ]