FROM docker:27.3.1-alpine3.20 AS docker

RUN /usr/local/bin/dockerd-entrypoint.sh || exit 0


FROM golang:1.22-alpine3.20 AS Coder

COPY --from=docker /certs /certs

RUN apk update && \
    apk add --no-cache \
    gcc \
    musl-dev \
    make \
    bash \
    bash-completion

COPY . /src/stamus-ctl

WORKDIR /src/stamus-ctl

RUN make && cp dist/* /bin && \
    stamusctl completion bash > /etc/profile.d/stamusctl_completion.sh && \
    echo "source /etc/profile.d/stamusctl_completion.sh" >> ~/.bashrc

ENTRYPOINT [ "bash" ]