
docker cli:
    stage: build
    image: docker:24.0.5
    variables:
        DOCKER_HOST: tcp://docker:2376
        DOCKER_TLS_CERTDIR: '/certs'
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: '$DOCKER_TLS_CERTDIR/client'
    services:
        - docker:24.0.5-dind
    needs:
        - unit tests
    before_script:
        - until docker info; do sleep 1; done
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build "${CI_PROJECT_DIR}"
          -t ${CI_REGISTRY_IMAGE}/cli:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
          -t ${CI_REGISTRY_IMAGE}/cli:${CI_COMMIT_BRANCH}
          -f "${CI_PROJECT_DIR}/docker/Dockerfile.cli"
        - docker push ${CI_REGISTRY_IMAGE}/cli:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
        - docker push ${CI_REGISTRY_IMAGE}/cli:${CI_COMMIT_BRANCH}

docker daemon:
    stage: build
    image: docker:24.0.5
    variables:
        DOCKER_HOST: tcp://docker:2376
        DOCKER_TLS_CERTDIR: '/certs'
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: '$DOCKER_TLS_CERTDIR/client'
    services:
        - docker:24.0.5-dind
    needs:
        - unit tests
    before_script:
        - until docker info; do sleep 1; done
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build "${CI_PROJECT_DIR}"
          -t ${CI_REGISTRY_IMAGE}/daemon:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
          -t ${CI_REGISTRY_IMAGE}/daemon:${CI_COMMIT_BRANCH}
          -f "${CI_PROJECT_DIR}/docker/Dockerfile.daemon"
        - docker push ${CI_REGISTRY_IMAGE}/daemon:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
        - docker push ${CI_REGISTRY_IMAGE}/daemon:${CI_COMMIT_BRANCH}

build cli:
    # image: git.stamus-networks.com:4567/lanath/lab/stamusctl-build-image:latest
    image: golang:alpine
    extends: .go-cache
    stage: build
    artifacts:
        expire_in: 1 day
        paths:
            - stamusctl
    needs:
        - unit tests
    script:
        - apk add --no-cache gcc musl-dev make
        - go install github.com/swaggo/swag/cmd/swag@latest
        - make cli
        - mv dist/stamusctl .

build daemon:
    # image: git.stamus-networks.com:4567/lanath/lab/stamusctl-build-image:latest
    image: golang:alpine
    extends: .go-cache
    stage: build
    artifacts:
        expire_in: 1 day
        paths:
            - stamusd
    needs:
        - daemon tests
    script:
        - apk add --no-cache gcc musl-dev make
        - go install github.com/swaggo/swag/cmd/swag@latest
        # - swag init --pd -g root.go -o cmd/docs -d cmd/daemon/run/
        - make daemon
        - mv dist/stamusd .

build test:
    # image: git.stamus-networks.com:4567/lanath/lab/stamusctl-build-image:latest
    image: golang:alpine
    extends: .go-cache
    stage: build
    artifacts:
        expire_in: 1 day
        paths:
            - outputs
            - cli
    needs:
        - unit tests
    script:
        - apk add --no-cache gcc musl-dev make
        - go install github.com/swaggo/swag/cmd/swag@latest
        - chmod +x $(pwd)/scripts/move.sh
        - $(pwd)/scripts/move.sh
        - make test-cli
        - mv .test/outputs outputs
        - mv dist/stamusctl cli
