includes:
  - nginx/config.yaml
  - subconfigs/elk.config.yaml

ArkimeviewerVersion:
  type: string
  usage: Arkime version to install
  default: master

volumepath:
  type: string
  usage: Path where data will be stored
  default: ./containers-data

RestartMode:
  type: string
  usage: Restart mode for services  
  default: unless-stopped
  choices: restartModes

MLEnabled:
  type: bool
  usage: Enable or disable Machine Learning  
  default: false

InterfacesList:
  type: string
  usage: List of interfaces to monitor  
  choices: interfaces

Registry:
  type: string
  usage: Docker registry to use  
  default: ghcr.io/stamusnetworks

scirius:
  version:
    type: string
    usage: Scirius version to install    
    default: selks
  token:
    type: string
    usage: Scirius token    
    default: ""

DebugMode:
  type: bool
  usage: Enable debug mode  
  default: false